module.exports={
	Admin: require('./views/Admin'),
	Array: require('./views/Array'),
	ButtonFlow: require('./views/ButtonFlow'),
	Byop: require('./views/Byop'),
	Byop2016: require('./views/Byop2016'),
	ByopNumbers: require('./views/ByopNumbers'),
	ByopPlayers: require('./views/ByopPlayers'),
	ByopSponsors: require('./views/ByopSponsors'),
	ByopTeamEditor: require('./views/ByopTeamEditor'),
	ByopWaitingListSwap: require('./views/ByopWaitingListSwap'),
	Division: require('./views/Division'),
	DivisionDropdown: require('./views/DivisionDropdown'),
	Footer: require('./views/Footer'),
	Header: require('./views/Header'),
	Home: require('./views/Home'),
	Json: require('./views/Json'),
	JsonProperty: require('./views/JsonProperty'),
	List: require('./views/List'),
	Literal: require('./views/Literal'),
	Login: require('./views/Login'),
	ManageByop: require('./views/ManageByop'),
	ManageDiscTypes: require('./views/ManageDiscTypes'),
	Toast: require('./views/Toast'),
	TypeAhead: require('./views/TypeAhead')
}