module.exports={
	Admin: require('./views/Admin'),
	ButtonFlow: require('./views/ButtonFlow'),
	Byop: require('./views/Byop'),
	ByopFriday: require('./views/ByopFriday'),
	ByopNumbers: require('./views/ByopNumbers'),
	ByopPlayers: require('./views/ByopPlayers'),
	ByopPlayersFriday: require('./views/ByopPlayersFriday'),
	ByopTeamEditor: require('./views/ByopTeamEditor'),
	ByopWaitingListSwap: require('./views/ByopWaitingListSwap'),
	Division: require('./views/Division'),
	DivisionDropdown: require('./views/DivisionDropdown'),
	Footer: require('./views/Footer'),
	Header: require('./views/Header'),
	Home: require('./views/Home'),
	Login: require('./views/Login'),
	ManageByop: require('./views/ManageByop'),
	Toast: require('./views/Toast'),
	TypeAhead: require('./views/TypeAhead')
}