# file: postgresql/tasks/users.yml

- name: PostgreSQL | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{user.name}}"
    password: "{{ user.pass | default(omit) }}"
    encrypted: "{{ user.encrypted | default(omit) }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{ user.databases }}"
  loop_control:
    loop_var: database
  when: database.type is defined and database.type == "postgres"

- name: Make sure PostgreSQL databases are present
  include: databases.yml
  tags: [postgresql, postgresql-databases]
  with_items: "{{ user.databases }}"
  loop_control:
    loop_var: db
  when: db.type is defined and db.type == "postgres"

- name: Set PostgreSQL user privileges on each database
  include: users_privileges.yml
  tags: [postgresql, postgresql-users]
  with_items:
    - user.databases
  loop_control:
    loop_var: db
  when: db.type is defined and db.type == "postgres"
